# Generated by Django 3.1.14 on 2022-05-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summury',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
