# Generated by Django 4.0.1 on 2022-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclama',
            name='body',
            field=models.TextField(default='S'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclama',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
